### ISSUE TITLE
Cb0t doesn show the room

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/cb0t#11]
Hello,

the newest Cb0t doesnt show when I join to a room.

PD.: I would be great if ghost or hollow87 answer me where can I put my programming questions.

**Comment by ohgoshdean** [comment]
Nemo,

Programming questions regarding cb0t/sb0t - there is no where for such questions. Github issues are ONLY for issues with the applications (ie. bugs).

For general programming questions, there are a number of online communities (ie. stackoverflow.com).

**Comment by hollow87** [comment]
Please provide more information on this issue as I can not reproduce.
