### ISSUE TITLE
fix cbot 3.37

### ISSUE THREAD

**Issue by Cobreti1** [AresChat/cb0t#15]
hi stuart and hollow for some time i want to install cbot 3.37 I can not have win 7 x64 bits, i hope i fix it and update cbot files that help describe the problem:
 C:\Users\usuario\AppData\Local\Temp\WER9A7E.tmp.WERInternalMetadata.xml
  C:\Users\usuario\AppData\Local\Temp\WERBB76.tmp.appcompat.txt
  C:\Users\usuario\AppData\Local\Temp\WERBCCF.tmp.mdmp

**Comment by hollow87** [comment]
What is the error that you get?

**Comment by Cobreti1** [comment]
help describe the problem:
C:\Users\usuario\AppData\Local\Temp\WER9A7E.tmp.WERInternalMetadata.xml
C:\Users\usuario\AppData\Local\Temp\WERBB76.tmp.appcompat.txt
C:\Users\usuario\AppData\Local\Temp\WERBCCF.tmp.mdmp

after install  open crash cbot dont run, grettings hallow
