### ISSUE TITLE
Heeeeelpp, I need a mechanic

### ISSUE THREAD

**Issue by Dawndonyou** [AresChat/cb0t#19]
To the cb0t Gods, 
My cb0t needs a tune-up please, It's unable to connect to ANY chatroom, Everything else SEEMS to work fine, it loads the rooms list but refuses to enter, like leading a horse to water and having it refuse to drink, ugh, tisk, tisk, so can you please fix it, work yo magic, please, *bows to you, 
Amen, thank you, love you, bless you in advance :)

**Comment by hexa2017** [comment]
Debes actualizar el archivo, **"servers.dat",** que se encuentra ubicado en la ruta **"C:\Users\emi\AppData\Local\cb0tv3\data"**
Acá comparto ese archivo para la descarga. 
[https://1drv.ms/u/s!AvFODEM66AA5jDOfu81qEDM8vMmh?e=Q6mvdu](url)

**Comment by hexa2017** [comment]
Olvidé decir que no uses el modo **web** para buscar salas, ya que se encuentra mal eso.

**Comment by Dawndonyou** [comment]
muchas gracias pero ese archivo no esta, donde puedo reinstalarlo, tienes un link para instalar cb0t?

**Comment by hexa2017** [comment]
Acá encontrarás cb0t.exe v3.39.

https://github.com/AresChat/cb0t/releases
[https://opengraph.githubassets.com/4d6e98c850de068a59a4f96d39fd66bfd0a85cdfd3bc5c02018172b2a415613c/AresChat/cb0t]<https://github.com/AresChat/cb0t/releases>
Releases · AresChat/cb0t<https://github.com/AresChat/cb0t/releases>
An alternative client used to connect to Ares chatrooms - AresChat/cb0t
github.com
La aplicación ya no funciona para buscar salas de chat por web.
Tiene un error interno que no ha sido reparado.
Así que no uses esa opción o habrá error.

Si no cargan salas luego de instalar cb0t, debes reemplazar los archivos "servers.dat" y "cache.dat" en la ruta, "C:\Users\Dawndonyou\AppData\Local\cb0tv3\data"
Puedes descargar los archivos en el link abajo, los acabo de actualizar a hoy.

https://1drv.ms/u/s!AvFODEM66AA5jDdU3su3OPQiSEsD?e=FtqYMo


Hecho todo lo anterior, solo queda cerrar y abrir la aplicación.

________________________________
De: Dawndonyou ***@***.***>
Enviado: lunes, 13 de febrero de 2023 01:05 p. m.
Para: AresChat/cb0t ***@***.***>
CC: naru ***@***.***>; Comment ***@***.***>
Asunto: Re: [AresChat/cb0t] Heeeeelpp, I need a mechanic (Issue #19)


muchas gracias pero ese archivo no esta, donde puedo reinstalarlo, tienes un link para instalar cb0t?

**Comment by sgatland** [comment]
Hello,

I'll update the servers.dat again

**Comment by sgatland** [comment]
I have fixed both the web version and the servers.dat from updating. This shouldn't happen in the future.
