### ISSUE TITLE
Unbanabblelizer or Sb0t Injecter

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/cb0t#3]
Hello thispixel,

can you do an Unbanabbelizer? It means a programm that make you unbanabble. Remember you are the builder of Sb0t :)
If you dont want to do an Unabanabbelizer... can you do a Sb0t injecter? It means a programm that can inject Code to a Sb0t-Server.

Thanks :)

**Comment by ghost** [comment]
I don't know what that is, the server supports plugins and has javascript support.

**Comment by Nemo2478** [comment]
Hello thispixel,

at first I must to say that is a honor to write you. You maked very good programms like Sb0t Crasher.

With Unbanabblelizer I mean a Programm that allows you that the admin from a server cant ban you.
And with Sb0t Injecter I mean a Programm that allows to inject Code into a Sb0t-Server.

But if you want to do that.. can you help me to do the following:

i tryed to write a script for Cb0t. The model are here: https://cb0t.codeplex.com/wikipage?title=Room

Its related to print:
print

Type: function
Return: void
Description: send a local announcement to the chat screen
Argument 1: string

roomobj.print("hello world");

I wanted with a command like /senprint send a print.

Can you help. Can you do it?

Thanks my friend :) (y)

**Comment by ghost** [comment]
The "Unbanabblelizer" as you call it, would be going against everything that I work for. If you're banned from a room it is for a reason and I'm certainly not going to write any code which allows users to bypass that.

You can use

```
Events.ontextsending(function (roomobj, text) {
    return text;
});
```

**Comment by Nemo2478** [comment]
f

**Comment by Nemo2478** [comment]
I....... understand. But I must to say you the following reality. Today, the admins doesn administrate the room. It appears that they abuse of their powers. They ingrain fear and they humiliate.

To the Javascript:

I can not add Scripts to Cb0t. What is the correctly way to add scipts to Cb0t?
Could you do this script and upload it? :) :)

Thanks
