### ISSUE TITLE
Know the OS

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/cb0t#5]
Hello thispixel,

can you do a Cb0t that allows to know the Operating System of a Sb0t?

Thanks :)

**Comment by ghost** [comment]
there is no reason to know what os the room is on

**Comment by Nemo2478** [comment]
Why? Its not interesting?

**Comment by ghost** [comment]
It is simply not required.

**Comment by Nemo2478** [comment]
Ok. YouTube are in reas on :(
Ich See that I will have never fun with Cb0t. I think I will add functions for Sb0t. Howard can I release Sb0t?

**Comment by ghost** [comment]
Create a fork and give the fork to whomever
