### ISSUE TITLE
print.js

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/cb0t#7]
Hello,

I make print.js with the following code:

Events.ontextsending(function (roomobj, text) {
    return text;
});

But it doesnt work. I dont send a print to the room. Can you help me thispixel please?

Thanks :)

**Comment by Nemo2478** [comment]
Thispixel,

I thought that print and HTML - injection can be seen from all the users of a chatroom.
How can I  achieve this?

Thanksort :)

**Comment by ghost** [comment]
You can't

**Comment by Nemo2478** [comment]
And I have a question thispixel:

why I am receiving an id from Sb0t when I connect. It there a way to not get an id by a Sb0t - Server?

Thanks:)
